<a href="https://colab.research.google.com/github/pragati2122/CE605A/blob/main/CE605A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1. Create a row and column vector using input method and manually.
rows,cols = 1,5
matrix_input = []
for i in range(rows):
    # Get the first row input in one go
    values = input(f"Enter {cols} values for {i+1} row separated by spaces: ").split()
    matrix_input.append(values)
row_vec_input = np.array(matrix_input)# Convert the list of lists to a NumPy array

rows,cols = 5,1
matrix_input = []
for i in range(cols):
    # Get the first row input in one go
    values = input(f"Enter {rows} values for {i+1} column separated by spaces: ").split()
    matrix_input.append(values)
column_vec_input = np.array(matrix_input)# Convert the list of lists to a NumPy array


Enter 5 values for 1 row separated by spaces:  1 2 3 4 5
Enter 5 values for 1 column separated by spaces:  1 2 3 4 5


In [ ]:
# 1. Create a row and column vector manually.
row_vec_manual = np.array([[1, 2, 3, 4, 5]])
col_vec_manual = row_vec_manual.reshape(-1,1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# 2. Using input method to create a matrix
rows,cols = 5,5
matrix_input = []
for i in range(rows):
    # Get the first row input in one go
    values = input(f"Enter {rows} values for {i+1} row separated by spaces: ").split()
    matrix_input.append(values)
a = np.array(matrix_input)# Convert the list of lists to a NumPy array
np.save("a.npy", a)

In [ ]:

# 2. using manual method to create a 5 by 5 matrix
matrix_manual = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 15, 17],
    [16, 17, 18, 19, 22],
    [24, 28, 23, 29, 21]
])
a=matrix_manual # saving with the name a1 so that the names are different
#np.save("a.npy", a)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 15, 17],
       [16, 17, 18, 19, 22],
       [24, 28, 23, 29, 21]])

In [ ]:
# 3 & 4 Extracting 3rd row and fourth column of matrix a
third_row = a[2, :]
fourth_column=a[:, 3]
print(f"third row: {third_row}")
print(f"fourth column: {fourth_column}")

third row: [11 12 13 15 17]
fourth column: [ 4  9 15 19 29]


In [ ]:
# 5. Sort matrix row-wise and column-wise
sorted_row_matrix = np.sort(a, axis=1)
sorted_col_matrix = np.sort(a, axis=0)
print(f"Sorted Row-Wise Matrix: {sorted_row_matrix}")
print(f"Sorted Column-Wise Matrix:{sorted_col_matrix}")

Sorted Row-Wise Matrix: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 15 17]
 [16 17 18 19 22]
 [21 23 24 28 29]]
Sorted Column-Wise Matrix:[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 15 17]
 [16 17 18 19 21]
 [24 28 23 29 22]]


In [ ]:
#  6. Apply for loop in matrix, if element is greater than 2, multiply element by 10 say it as “b”.
matrix=a
rows,column=a.shape
for i in range(rows):
    for j in range(column):
        if matrix[i, j] > 2:
            b[i, j] = matrix[i, j] * 10
        else:
            b[i, j] = matrix[i, j]
print(f"b: {b}")

b: [[  1   2  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 150 170]
 [160 170 180 190 220]
 [240 280 230 290 210]]


In [ ]:
# 7. add matrix a and b
result = a + b
print(f"Result of a + b: {result}")

Result of a + b: [[  2   4  33  44  55]
 [ 66  77  88  99 110]
 [121 132 143 165 187]
 [176 187 198 209 242]
 [264 308 253 319 231]]


In [ ]:
# 8. subtract b from a
result1 = a - b
print(f"Result of a - b: {result1}")

Result of a - b: [[   0    0  -27  -36  -45]
 [ -54  -63  -72  -81  -90]
 [ -99 -108 -117 -135 -153]
 [-144 -153 -162 -171 -198]
 [-216 -252 -207 -261 -189]]


In [ ]:
# 9. Multiply matrix a by b element wise and matrix multiplication
element_wise_result = a * b # Element-wise multiplication
matrix_mult_result = np.dot(a, b)# Matrix multiplication
print(f"Element-wise multiplication:{element_wise_result}")
print(f"Matrix multiplication:{matrix_mult_result}")


Element-wise multiplication:[[   1    4   90  160  250]
 [ 360  490  640  810 1000]
 [1210 1440 1690 2250 2890]
 [2560 2890 3240 3610 4840]
 [5760 7840 5290 8410 4410]]
Matrix multiplication:[[ 2291  2582  2450  2880  2690]
 [ 5146  5792  5700  6680  6440]
 [ 8641  9732  9590 11250 10830]
 [11336 12772 12660 14860 14360]
 [13914 15578 16000 18530 18700]]


In [ ]:
# 10. Divide each element of matrix a and b by 18
a_divided = a / 18
b_divided = b / 18
print(f"Matrix a:{a_divided}")
print(f"Matrix b:{b_divided}")

Matrix a:[[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.33333333 0.38888889 0.44444444 0.5        0.55555556]
 [0.61111111 0.66666667 0.72222222 0.83333333 0.94444444]
 [0.88888889 0.94444444 1.         1.05555556 1.22222222]
 [1.33333333 1.55555556 1.27777778 1.61111111 1.16666667]]
Matrix b:[[ 0.05555556  0.11111111  1.66666667  2.22222222  2.77777778]
 [ 3.33333333  3.88888889  4.44444444  5.          5.55555556]
 [ 6.11111111  6.66666667  7.22222222  8.33333333  9.44444444]
 [ 8.88888889  9.44444444 10.         10.55555556 12.22222222]
 [13.33333333 15.55555556 12.77777778 16.11111111 11.66666667]]


In [ ]:
# 11. find the inverse, rank, condition number, singular value decomposition and the norm of matrices
# a and b.

# inverse of matrices a and b
a_inv = np.linalg.inv(a)
b_inv = np.linalg.inv(b)

# rank of matrices a and b
a_rank = np.linalg.matrix_rank(a)
b_rank = np.linalg.matrix_rank(b)

# condition number of matrices a and b
a_cond = np.linalg.cond(a)
b_cond = np.linalg.cond(b)

# Singular Value Decomposition on matrices a and b
a_u, a_s, a_vt = np.linalg.svd(a)
b_u, b_s, b_vt = np.linalg.svd(b)

# norm of matrices a and b
a_norm = np.linalg.norm(a, 'fro')
b_norm = np.linalg.norm(b, 'fro')

print("Inverse of matrix a:")
print(a_inv)

print("Inverse of matrix b:")
print(b_inv)

print("Rank of matrix a:", a_rank)
print("Rank of matrix b:", b_rank)

print("Condition number of matrix a:", a_cond)
print("Condition number of matrix b:", b_cond)

print("Singular Value Decomposition of matrix a:")
print("U:", a_u)
print("S:", a_s)
print("V^T:", a_vt)

print("Singular Value Decomposition of matrix b:")
print("U:", b_u)
print("S:", b_s)
print("V^T:", b_vt)

print("norm of matrix a:", a_norm)
print("norm of matrix b:", b_norm)

Inverse of matrix a:
[[-1.73333333e+00  7.33333333e-01  1.22222222e+00 -7.77777778e-01
  -1.11111111e-01]
 [ 2.86666667e+00 -2.86666667e+00 -1.44444444e+00  1.55555556e+00
   2.22222222e-01]
 [-1.33333333e+00  2.83333333e+00 -7.77777778e-01 -2.77777778e-01
  -1.11111111e-01]
 [-1.00000000e+00  1.00000000e+00  1.00000000e+00 -1.00000000e+00
   9.71445147e-17]
 [ 1.00000000e+00 -1.50000000e+00  5.75928194e-16  5.00000000e-01
  -7.63278329e-17]]
Inverse of matrix b:
[[ 0.06666667 -0.22666667  0.02222222  0.06222222  0.00888889]
 [-0.11025641  0.20948718  0.02094017 -0.07598291 -0.0108547 ]
 [ 0.05128205  0.0525641  -0.15470085  0.07991453  0.0042735 ]
 [ 0.03846154 -0.07307692  0.04230769 -0.01923077  0.01153846]
 [-0.03846154  0.02307692  0.05769231 -0.03076923 -0.01153846]]
Rank of matrix a: 5
Rank of matrix b: 5
Condition number of matrix a: 488.95680213636507
Condition number of matrix b: 280.06462535565623
Singular Value Decomposition of matrix a:
U: [[-0.08744498 -0.29086377  0.7028

In [ ]:
# 12. ind the norm, inner product and outer product of column vector.

v= fourth_column # Column Vector
norm_v = np.linalg.norm(v)
inner_product_v = np.dot(v.T, v)
outer_product_v = np.outer(v, v.T)
print("Norm of v:", norm_v)
print("Inner product of v with itself:", inner_product_v)
print("Outer product of v with itself:")
print(outer_product_v)


Norm of v: 39.03844259188627
Inner product of v with itself: 1524
Outer product of v with itself:
[[ 16  36  60  76 116]
 [ 36  81 135 171 261]
 [ 60 135 225 285 435]
 [ 76 171 285 361 551]
 [116 261 435 551 841]]


In [ ]:
# 13. Write a function called derivative which takes input parameters f(x), a, method (forward,backward
# and central) and h(step size) (with default values method=‘central’ and h = 0.01) and returns the
# corresponding difference formula for derivative of function at a with step size h and then test your
# function on e
# x and cos x at x = 0.5.

method="central"
h = 0.01
a=0.5

def f_exponential(a):
    return np.exp(a)
def f_cos(a):
    return np.cos(a)

def derivative(f, a, method, h):
    if method =="central":
        return (f(a + h) - f(a - h)) / (2 * h)
    else:
        raise ValueError("Invalid method: Function only for central method")

# Test the function on e^x and cos(x) at x = 0.5
x = 0.5
if derivative(f_exponential, x, method, h) == f_exponential(x):
    print("True")
else:
    print("False")

# Test the function on e^x and cos(x) at x = 0.5 upto 4 decimals only
if round(derivative(f_exponential, x, method, h), 4) == round(f_exponential(x), 4):
    print("The derivative function works.")
else:
    print("The derivative function does not work.")


False
True


In [ ]:
# 14. Download the Automatic Weather Station AWS Data. Read the .csv file using pandas library as a DataFrame.

import pandas as pd
file_path = r'D:/Stats_Course/AWS.csv'

df = pd.read_csv(file_path) # Read the CSV file into a DataFrame
print(df.head()) # Display the first few rows of the DataFrame

                  created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15  
